name: Lint

on:
    push:
      branches:
        - main
        - tesis/main
    pull_request:
      branches:
        - main
        - tesis/main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Cambia esto a tu versión de Node.js

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn eslint . --fix
